# language: node_js

# #if you want to specify a particular node.js version
# node_js:
#   - 14 

# before_install:
# - pyenv install 3.6.0

# install:
# - npm install
# - cd src/backend/
# - python3 -m pip install --upgrade pip
# - pip install -r requirements.txt

# script:
matrix:
  include:
  - language: node_js

    install:
      - npm install
    
    script: 
      - npm run build

  - language: python3

    before_install:
      - cd src/backend/

    install:
      - pip install -r requirements.txt

    script: 
      - pytest